### ISSUE TITLE
Ну.. это несколько не то, что подразумевалось

### ISSUE THREAD

**Issue by pavel-b-novikov** [re-gor/nsudotnet#1]
Вот сейчас возьмите свой код, внимательно на него посмотрите и подумайте как вы будете переиспользовать его для графического приложения?
У вас есть классы Game, Cell и т.п. - прекрасно. И как, например, сделать ход "извне" приложения? Ну т.е. я начал писать графический фронтенд для этих классов. Круто. Как мне проинформировать логику о том, что сделан ход, если логика сама запрашивает новый ход с консоли? А у графического приложения в общепринятом понимании консоли нет (ну она есть, но пользователю до неё доступиться проблемно). IField предоставляет всего 2 проперти наружу. И вот вы как хотите, а я не смогу с их помощью сделать графическую обертку.
Переинженирьте это, пожалуйста.

**Comment by re-gor** [comment]
Действительно. Переделаю этот момент

UPD. На самом деле всё не так критично. Давно код не видел - чуть потупил. 

Есть метод bool TryPutValue(..). Если проставить не получается вернет False ну или Exception. По тому, что получается можно отследить, что внутри происходит.
Непонятно почему я его в интерфейс не внес. Та причина, которую я себе придумал - не причина, на самом деле=) 

Добавлю в интерфейс еще GetFieldStatus. Отдаст квадратный массив из крестиков и ноликов

**Comment by pavel-b-novikov** [comment]
(это тестовый комментарий, не надо на него отвечать)
