### ISSUE TITLE
[TicTacToe] Все те же яйца

### ISSUE THREAD

**Issue by pavel-b-novikov** [re-gor/nsudotnet#2]
... только сбоку.
Егор, не должен быть класс задачи статическим. Ну не-дол-жен! Как вы его будете тестировать? Как вы на него напишете unit-тест, как заинжектите в IoC на живом решении? Как подключите к MVC в случае если (не дай б-же) решите делать онлайн-версию?
Егор, соберитесь. Вы можете. Еще раз.
Избавьтесть от статики, вынесите все значимые методы за интерфейс и оформите всю игруню как реализацию интерфейса.

**Comment by re-gor** [comment]
Нене, все нормально.

Да у меня тут попа с названиями. Из-за этого, наверное, непонятно.

Класс игры (которая вот совсем игра) лежит в отдельной сборке. Сейчас закомичу интерфейс к ней. 

Статический класс игры это консольная обертка - там только вывод в консоль и обработка ошибок ввода сообщениями в стандартный вывод.

**Comment by re-gor** [comment]
Попа заключается в том, что есть два одинаково названных класса в разных намспэйсах.

**Comment by pavel-b-novikov** [comment]
Ну так назовите нормально. А то же ничего жешь не понять

**Comment by re-gor** [comment]
Ну я фиг его знает, как назвать "игру" по-другому. В принципе у меня с называнием беда =(. Подумал, что namespace'ы, в том числе, для этого и сделаны. 
Bykhovtsev.Nsudotnet.TicTacToeConsole - все, что привязано к консоли 
Bykhovtsev.Nsudotnet.TicTacToe - сама игра

**Comment by pavel-b-novikov** [comment]
Ну так нормально, просто лежит в несоответствующих папках.

**Comment by pavel-b-novikov** [comment]
Так.. а почему у вас IGame и IField, которые делают вроде то же самое?

**Comment by re-gor** [comment]
Ну нет.
IGame уже содержит логику игры. Знает о том, что есть поле, есть подполя, есть игроки, есть типы ходов для этих игроков

Согласен, что IGame можно отнаследовать от IField, ну или заставить Game реализовать оба с выкидыванием пересечения. Правда тогда надо в IField переименовать  метод 
Symbol[,] GetFieldStatus(); 
либо наоборот 
Symbol[,] GetGameField(); 
в IGame

**Comment by pavel-b-novikov** [comment]
Мой вопрос был не из разряда "как?", а из разряда "зачем?"

**Comment by re-gor** [comment]
Ну тогда первые три строчки.

**Comment by pavel-b-novikov** [comment]
Что первые три строчки? :)

**Comment by re-gor** [comment]
Три первые строчки из ответа:

> Ну нет.
> IGame уже содержит логику игры. Знает о том, что есть поле, есть подполя, есть игроки, есть типы ходов для этих игроков

Ниже про остальные строчки (можно не читать =) )
Строго говоря ни то, ни то нельзя сделать. Я хочу IField оставить внутренним для сборки. 
Следовательно наследовать public IGame от него нельзя: ругнется на уровень доступности.
Опять же заставить Game его реализовывать нельзя: для IoC не подойдет

**Comment by pavel-b-novikov** [comment]
Слушайте, мой вопрос был про то, нужен ли IField вообще. Но да ладно.

**Comment by re-gor** [comment]
Сейчас от него практической пользы никакой.
Извините, что сразу не понял вопроса.
