### ISSUE TITLE
[TicTacToe] Структуры

### ISSUE THREAD

**Issue by pavel-b-novikov** [re-gor/nsudotnet#3]
Расскажите мне вот еще какой нюанс. Вижу что Cell изначально была структурой. Работает ли это сейчас? Объясните свой выбор в пользу структуры. Да еще и из одного (по факту) поля. Только честно.

**Comment by re-gor** [comment]
Ну так она структурой и осталась и даже используется:

``` c#
 class SubField : IField
    {
        #region Fields
        private Cell[,] _cells = new Cell[3,3];
        private byte _fullCellsCounter = 0;

        /*остальной код*/
    }
```

Структура, потому что легкая, хранится в стеке и содержит в себе содержит только enum, который хранится на стеке. Решил, что заводить тут класс это слишком "круто". К enum есть пачка методов и нужное свойство: 

``` c#
public Symbol Value
        {
            get
            {
                return _value;
            }
            set
            {
                if (_value != Symbol.Empty)
                    throw new InvalidOperationException("Cell value is not empty. You can not put another value");

                _value = value;
            }
        }
```

И еще куча операторов для нормальной интерпритации Cell, как Symbol.
Еще из полезного от него, что при дебаге в отладчике переменные красиво пишутся (X O)

**Comment by pavel-b-novikov** [comment]
Ну вот в качестве доп. задания - сделайте так, чтобы Cell кастилась к Symbol явно и неявно.

**Comment by re-gor** [comment]
Задача зачтена?

**Comment by pavel-b-novikov** [comment]
Да. Получите у Семена зачет.

2015-05-18 10:31 GMT+06:00 Bykhovtsev Egor notifications@github.com:

> Задача зачтена?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/re-gor/nsudotnet/issues/3#issuecomment-102919761.

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447
